export const checkboxOptions = [
	{ key: 'Agriculture', value: 'agriculture' },
	{ key: 'Animals', value: 'animals' },
	{ key: 'Arts', value: 'arts' },
	{ key: 'Books & Literature', value: 'books literature' },
	{ key: 'Business', value: 'business' },
	{ key: 'Entertainment', value: 'entertainment' },
	{ key: 'Foods & beverages', value: 'foods beverages' },
	{ key: 'Human Resource', value: 'human resource' },
	{ key: 'Innovations', value: 'innovations' },
	{ key: 'Jobs', value: 'jobs' },
	{ key: 'Life & Style', value: 'life and style' },
	{ key: 'Oil & mining', value: 'oil and mining' },
	{ key: 'Politics', value: 'politics' },
	{ key: 'Popular', value: 'popular' },
	{ key: 'Science', value: 'science' },
	{ key: 'Spiritual', value: 'spiritual' },
	{ key: 'Sports', value: 'sports' },
	{ key: 'Technology', value: 'techonology' },
	{ key: 'Transport', value: 'transport' },
	{ key: 'Travel', value: 'travel' },
	{ key: 'Tv', value: 'tv' },
	{ key: 'World', value: 'world' },
	{ key: 'Yoga', value: 'yoga' },
	{ key: 'Youth', value: 'youth' },
	{ key: 'Industrial Relation', value: 'industries' },
	{ key: 'IT', value: 'IT' },
	{ key: 'Manufacturing', value: 'manufacturing' },
	{ key: 'Media', value: 'media' },
	{ key: 'Medical', value: 'medical' },
	{ key: 'People', value: 'people' },
	{ key: 'Photography', value: 'photography' },
	{ key: 'Police & crime', value: 'crime' },
	{ key: 'Research', value: 'research' },
	{ key: 'Banking', value: 'banking' },
	{ key: 'Biotechnology', value: 'biotechnology' },
	{ key: 'Breaking News', value: 'breaking news' },
	{ key: 'Community', value: 'community' },
	{ key: 'Education', value: 'education' },
	{ key: 'Engineering', value: 'engineering' },
	{ key: 'Fitness', value: 'fitness' },
	{ key: 'Games', value: 'games' },
	{ key: 'Tourism', value: 'tourism' },
	{ key: 'Government', value: 'government' },
];
